name: facerecognition_flutter
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  facesdk_plugin:
    path: ./facesdk_plugin
  http: ^1.2.0
  sqflite: ^2.3.2
  path: ^1.8.3
  geolocator: ^11.0.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  dio: ^5.4.0
  mac_address: ^1.0.0
  android_id: ^0.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_exif_rotation: ^0.5.1
  go_router: ^13.0.1
  intl: ^0.19.0
  flutter_lints: ^3.0.1
  image_picker: ^1.0.7
  connectivity_plus: ^5.0.2
  file_picker: ^6.1.1
  flutter_launcher_icons: "^0.13.1"
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2

flutter_launcher_icons:
  android: ic_launcher
  image_path: "assets/ic_launcher.png"
  adaptive_icon_background: "assets/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

